### ISSUE TITLE
Error de logo ASES en descarga de seguimientos

### ISSUE THREAD

**Issue by sistemasases** [sistemasases/sistema_informacion_ASES#120]
Corregir el bug que pone la pantalla en blanco al dar click al logo de ASES que se encuentra en la esquina superior izquierda. Solo ocurre este error si se está en la vista de "descarga de fichas"

**Comment by Dalex11** [comment]
Corregido: https://github.com/sistemasases/sistema_informacion_ASES/tree/fixing_deiby
Rama de la corrección: fixing_deiby
