### ISSUE TITLE
Crear vista de Alertas por estudiante

### ISSUE THREAD

**Issue by sistemasases** [sistemasases/sistema_informacion_ASES#21]
Crear vista de alertas por estudiante: Es una vista similar a la del reporte general, pero solo debe tener la información general del estudiante y un listado de las alertas que tiene activas en este momento.

Al darle click al estudiante también debe mandar a la ficha del mismo.

Debe permitir descargar en csv y excel.

Tipos de alertas:
-Acuerdo de tratamiento de datos
-Encuesta de admitidos
-Ficha realizada la semana anterior
-Dimensión En riesgo alto. (por cada dimensión)
-Mensaje del profesional
-Mensaje del practicante
-Alerta académica 

Preguntar a César para que explique de qué trata cada alerta.

**Comment by iMrStevenS2** [comment]
## _Creación de tabla en vista de alertas_ 
### 3/7 aspectos cubiertos dentro de la tabla, los demás se encuentran en espera:

- [x] Acuerdo de tratamiento de datos
- [ ] Encuesta de admitidos
- [x] Ficha realizada la semana anterior
- [x] Dimensión En riesgo alto. (por cada dimensión)
- [ ] Mensaje del profesional
- [ ] Mensaje del practicante
- [ ] Alerta académica

#### *Botones de descarga en progreso*.

**Comment by sistemasases** [comment]
Done #111
