### ISSUE TITLE
Añadir ícono de alerta con sumatoria al navbar

### ISSUE THREAD

**Issue by sistemasases** [sistemasases/sistema_informacion_ASES#24]
Añadir ícono de alertas, con el número de alertas de los estudiantes del usuario, en la navbar. Al darle click al ícono este debe dirigir a la vista de alertas por estudiante.

**Comment by iMrStevenS2** [comment]
### **Contadores completados:**
- [x]    _Riesgos_ 
- [x]    _Tratamiento de Datos_ 
- [ ]    _Encuesta de admitidos_ 
- [x]    _Semanal - Tabla de Inasistencias_ 
- [ ]    _Académicos_

**Comment by iMrStevenS2** [comment]
### Cambio en método de consulta realizado.
#### _25/10/2023_

**Comment by sistemasases** [comment]
Done #111
