### ISSUE TITLE
Actualizar links enviados por Paula

### ISSUE THREAD

**Issue by sistemasases** [sistemasases/sistema_informacion_ASES#34]
Dentro de la página de ASES, en la sección de Investigación y difusión cambiar y corregir los link que fueron enviados por Paula.

Link página: https://ases.univalle.edu.co/investigaciones-ases

Solicitar a César el documento donde dice qué links cambiar.

Acceso: https://ases.univalle.edu.co/administrator/
Usuario Sistemas:
talentospilos_admin
Contraseña:
p1l0s%2016

**Comment by Jpcqaa2** [comment]
Corregido el error encontrado por Steven en una publicación.
