### ISSUE TITLE
Cambio en riesgos del estudiante.

### ISSUE THREAD

**Issue by sistemasases** [sistemasases/sistema_informacion_ASES#72]
Hacer que los riesgos que se reflejan en la ficha del estudiante no sean los del último seguimiento si no que se muestre la última vez que se trato cada dimensión.

-Crear modelo que agarre el ID del estudiante y cada uno de los riesgos.
-Hacer que al guardar o editar una ficha tambien actualice este modelo.
-Cabmiar las consultas que traen los riesgos del ultimo riesgo y en su lugar hacer que consulten el modelo creado.

**Comment by Dalex11** [comment]
Ya subí el cambio a la rama https://github.com/sistemasases/sistema_informacion_ASES/tree/issue-72

**Comment by sistemasases** [comment]
Done #95
